# Generated by Django 6.0.5 on 2026-05-15 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0002_entry_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='date_modification',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
